const REGISTER="user:REGISTER"
const LOGIN="user:LOGIN"
const GET_ALL_USERS="user:GET_ALL_USERS"
const GET_USER_BY_ID="user:GET_USER_BY_ID"
const UPDATE_USER="user:UPDATE_USER"
const DELETE_USER="user:DELETE_USER"
const RESET_PASSWORD = "user:RESET_PASSWORD"
const VIEW_OWN_REVIEWS="user:VIEW_OWN_REVIEWS"
const RESPOND_TO_USER_REVIEW="user:RESPOND_TO_USER_REVIEW"
const GET_ALL_BORROWING_BOOKS_OF_USER="user:GET_ALL_BORROWING_BOOKS_OF_USER"


const ADD_BOOK="book:ADD_BOOK"
const GET_ALL_BOOKS="book:GET_ALL_BOOKS"
const GET_BOOK_BY_ID="book:GET_BOOK_BY_ID"
const UPDATE_BOOK="book:UPDATE_BOOK"
const DELETE_BOOK="book:DELETE_BOOK"
const VIEW_AVAILABLE_BOOKS="book:VIEW_AVAILABLE_BOOKS"
const MONITOR_BOOK_STATUS="book:MONITOR_BOOK_STATUS"
const VIEW_BOOK_RATING="book:VIEW_BOOK_RATING"
const SEARCH_BOOKS="book:SEARCH_BOOKS"






const ADD_AUTHOR="author:ADD_AUTHOR"
const AUTHOR_LOGIN="author:AUTHOR_LOGIN"
const AUTHOR_RESETPASSWORD="author:AUTHOR_RESETPASSWORD"
const GET_AUTHOR_BY_ID="author:GET_AUTHOR_BY_ID"
const GET_AUTHORS_BOOKS="author:GET_AUTHORS_BOOKS"
const SEARCH_AUTHORS="author:SEARCH_AUTHORS"
const GET_ALL_AUTHORS="author:GET_ALL_AUTHORS"
const UPDATE_AUTHOR="author:UPDATE_AUTHOR"
const DELETE_AUTHOR="author:DELETE_AUTHOR"




const ADD_BORROWING="borrowing:ADD_BORROWING"
const GET_ALL_BORROWING="borrowing:GET_ALL_BORROWING"
const GET_BORROWING_BY_ID="borrowing:GET_BORROWING_BY_ID"
const VIEW_BORROWING_STATUS="borrowing:VIEW_BORROWING_STATUS"
const UPDATE_BORROWING="borrowing:UPDATE_BORROWING"
const CANCEL_BORROWING="borrowing:CANCEL_BORROWING"






const CREATE_REVIEW="review:CREATE_REVIEW"
const GET_ALL_REVIEWS="review:GET_ALL_REVIEWS"
const GET_REVIEW_BY_ID="review:GET_REVIEW_BY_ID"
const UPDATE_REVIEW="review:UPDATE_REVIEW"
const DELETE_REVIEW="review:DELETE_REVIEW"
const GET_BOOK_REVIEWS="review:GET_BOOK_REVIEWS"
const FLAG_INAPPROPRIATE_REVIEW="review:FLAG_INAPPROPRIATE_REVIEW"
const GET_REVIEW_STATISTICS="review:GET_REVIEW_STATISTICS"




const ADD_PUBLISHER="publisher:ADD_PUBLISHER"
const PUBLISHER_LOGIN="publisher:PUBLISHER_LOGIN"
const PUBLISHER_RESETPASSWORD="publisher:PUBLISHER_RESETPASSWORD"
const GET_ALL_PUBLISHERS="publisher:GET_ALL_PUBLISHERS"
const GET_PUBLISHER_BY_ID="publisher:GET_PUBLISHER_BY_ID"
const SEARCH_PUBLISHERS="publisher:SEARCH_PUBLISHERS"
const GET_PUBLISHER_BOOKS="publisher:GET_PUBLISHER_BOOKS"
const UPDATE_PUBLISHER="publisher:UPDATE_PUBLISHER"
const DELETE_PUBLISHER="publisher:DELETE_PUBLISHER"


module.exports={
    REGISTER,
    LOGIN,
    GET_ALL_USERS,
    GET_USER_BY_ID,
    UPDATE_USER,
    DELETE_USER,
    VIEW_OWN_REVIEWS,
    RESPOND_TO_USER_REVIEW,
    RESET_PASSWORD,
    GET_ALL_BORROWING_BOOKS_OF_USER,
    GET_BOOK_REVIEWS,
    VIEW_AVAILABLE_BOOKS,

    ADD_BOOK,
    GET_BOOK_BY_ID,
    GET_ALL_BOOKS,
    UPDATE_BOOK,
    DELETE_BOOK,
    VIEW_AVAILABLE_BOOKS,
    MONITOR_BOOK_STATUS,
   VIEW_BOOK_RATING,
   SEARCH_BOOKS,


   ADD_AUTHOR,
   AUTHOR_LOGIN,
   AUTHOR_RESETPASSWORD,
   GET_AUTHOR_BY_ID,
   GET_ALL_AUTHORS,
   GET_AUTHORS_BOOKS,
   SEARCH_AUTHORS,
   UPDATE_AUTHOR,
   DELETE_AUTHOR,

    ADD_BORROWING,
    GET_BORROWING_BY_ID,
    GET_ALL_BORROWING,
    VIEW_BORROWING_STATUS,
    UPDATE_BORROWING,
    CANCEL_BORROWING,

    CREATE_REVIEW,
    GET_ALL_REVIEWS,
    GET_REVIEW_BY_ID,
    UPDATE_REVIEW,
    DELETE_REVIEW,
    GET_BOOK_REVIEWS,
    FLAG_INAPPROPRIATE_REVIEW,
    GET_REVIEW_STATISTICS,

    ADD_PUBLISHER,
    PUBLISHER_LOGIN,
    PUBLISHER_RESETPASSWORD,
    GET_ALL_PUBLISHERS,
    GET_PUBLISHER_BY_ID,
    SEARCH_PUBLISHERS,
    GET_PUBLISHER_BOOKS,
    UPDATE_PUBLISHER,
    DELETE_PUBLISHER

}